### ISSUE TITLE
[bug] changing the language ask to restart the driver

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#1148]
Hydrogen version *          : GIT master 1bacb4a
Operating system + version  : LibraZiK-3 (debian buster based)
Audio driver + version      : auto (jackdriver)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

going to menu -> options -> Preferences ->General -> Language -> and changing the language, a first window pops up:

![fenetre1](https://user-images.githubusercontent.com/8705846/106385812-6264fe80-63d2-11eb-9e58-73ca0fa628f1.png)

which is fine, then, a second window pops up:

![fenetre2](https://user-images.githubusercontent.com/8705846/106385828-73157480-63d2-11eb-8609-127dd067f176.png)

which looks kind of strange from a user point of view:
- why do we need to change the audio driver for changing the language?
- why does it ask me to change the audio driver while I've to restart?

**Comment by theGreatWhiteShark** [comment]
How often do you have tried these steps?

Since we capitalized the acronyms of the audio drivers, the version of the string in your `hydrogen.conf` does not match anymore. This feels like a change to the `PreferencesDialog`. But this behavior should only happen once (including restart).

**Comment by trebmuh** [comment]
It's reproducible every time.
Note that if I erase the ~/.hydrogen/hydrogen.conf file, it still acts the same.

**Comment by theGreatWhiteShark** [comment]
Okay. Could you try it twice with #1149? I did some fixed in the `PreferencesDialog` and I can't reproduce it in that particular branch anymore. Maybe I fixed this issue as well.

**Comment by trebmuh** [comment]
@theGreatWhiteShark I'm sorry this one went outside of my view. I'll make myself some available time this coming week. #1149 seems to be already in master. I'll build from master tomorrow and will report here.

**Comment by trebmuh** [comment]
I've try with with a rebuild from master 4aa5668 and it is still the same.

**Comment by cme** [comment]
This is because the Midi port name "None" in the midi port combo boxes gets translated, and is the value saved in preferences (and "None") is special to the drivers. So when you change language, then restart, then change *any* preference, the value of "None" in Preferences may not match the "None" in the GUI, it thinks the driver needs a restart.

Oops.

**Comment by cme** [comment]
Reviewed Preferences.cpp for any similar issues, found one where the mixer falloff setting might become dependent on the translation of the speeds. Added a fix for that too.

**Comment by trebmuh** [comment]
:+1: I can confirm that this one is fixed with a fresh build from aa738c3
