### ISSUE TITLE
Sometimes Hydrogen gets caught.

### ISSUE THREAD

**Issue by melolontha-melolontha** [hydrogen-music/hydrogen#1351]
Hydrogen version *          : 0.9.7 [Sept 19 2017]
Operating system + version  : Xubuntu 18.04
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Sometimes Hydrogen gets caught. The time display then only continues to run very slowly (about 1/6 of the intended speed). The individual percussion beats then also sound distorted and very quiet.

In my experiments, the audio stream from Hydrogen in was fed into a Jamulus session via qJackCtl. But it just happened again without Jamulus running: I just paying attention to the uniformity of the pattern while doing other work on the computer and then it happened again at something like 23% CPU load and something 4 GiB unused memory.

In such a situation it is not enough to stop the playback. Changing the BPM rate also seems to have no influence. When I deleted the pattern and re-entered it, Hydrogen ran again. Also loading the same or a new pattern seems to bring back hydrogen to its normal operating mode.

I don't know how to trigger this bug. Once such a stall occurred when I didn't have my fingers on the computer at all: Neither the CPU nor the memory were at their limit at that moment. Another stall happened, when I muted my mike in Jamulus, but that might not really have been the cause for the stall.

Sometimes such a glitch disappears by itself (after a few seconds to a few minutes). No idea what is going on there.

Any Idea what to do if it happens again in order to give you hints about where the bug is?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by cme** [comment]
Hi,

Can you try a more recent Hydrogen? Many bugs have been fixed since 0.9.7 including ones that might cause behaviour like that. There are no plans to back-port any fixes from the 1.* releases to 0.9.*

**Comment by melolontha-melolontha** [comment]
Can version 1.0.0 also be installed in Ubuntu 18.04 despite [https://pkgs.org/download/hydrogen](https://pkgs.org/download/hydrogen) recommends hydrogen_0.9.7-6_amd64.deb ?

**Comment by theGreatWhiteShark** [comment]
Hey @melolontha-melolontha ,

Where you able to compile Hydrogen on you Xubuntu 18.04 device and does Hydrogen still get caught over there?

**Comment by melolontha-melolontha** [comment]
Unfortunately I was not able to get it run on Xubuntu 18.04. 

But I installed version 1.0.0-rc1 on a similar laptop (T430s) running Ubuntustudio 20.4 and I did not experience Hydrogen getting caught there.

**Comment by theGreatWhiteShark** [comment]
> But I installed version 1.0.0-rc1 on a similar laptop (T430s) running Ubuntustudio 20.4 and I did not experience Hydrogen getting caught there.

Very nice. I will close this issue for now. Please reopen it as soon as you encounter this problem again.
