### ISSUE TITLE
When zoomed out completely, adding a note using triplet resolution doesn't place the note where you click

### ISSUE THREAD

**Issue by JohnCPun** [hydrogen-music/hydrogen#366]
Windows 7 x64
Hydogen 0.9.7-windowsPreview [Aug 31 2015]

In pattern editor zoom out completely (using the - button).
Now change the size of the pattern to the max (32) and the resolution to 16T or 32T. 
Add a note on count 15.

Expected:
It is added on count 15

Observation:
It is added on count 16

The distance between where you click and where the note appears actually is relative to where you click. For example: if you add a note on count 8, it will show up on count 8.5.
It is also related to the resolution you select. At 32T it will behave the same way as at 16T but at 8T it really only starts showing around count 13.
When you zoom in just 1 level it will add the note where you click.

**Comment by pvint** [comment]
I can confirm this on Linux with latest git (Aug 25, 2016)

**Comment by pvint** [comment]
A fix to test out on pull request #403

**Comment by mauser** [comment]
Hi,
this is fixed now in the master branch..

**Comment by trebmuh** [comment]
@pvint and @mauser : sorry guys but fresh rebuild from today's git (https://github.com/hydrogen-music/hydrogen/commit/8869f5af04db6d8ad63aa1d45e45fe573cc27646) and this bug is still here. Let me know if I can be of any help with that.

**Comment by pvint** [comment]
Strange, I find the same thing on my desktop. 

I should be able to have a look on Friday.

Thanks for the report @trebmuh

**Comment by trebmuh** [comment]
No worries. Keep me in the loop.

**Comment by pvint** [comment]
Finally looking back on this again, and I must admit that I'm still a bit puzzled as I was perfectly confident it was tested well! It's still broken, and I will figure it out. 
Just too a quick refresher look at it tonight, and I think I will have to start right from the beginning where the grid is laid out and see how the grid width etc is all calculated.

More to come.

**Comment by pvint** [comment]
Note to self: I originally "fixed" this on my laptop - possibly something different there... QT maybe??

Note to anyone who has access: Can we re-open this issue since it is clearly not solved? Thanks!

**Comment by mauser** [comment]
Done!

**Comment by trebmuh** [comment]
Feel free to ping me if you need someone to test stuff @pvint

**Comment by pvint** [comment]
@trebmuh  After my previous failure, maybe it's best that someone else tests this this time! ;)
If you have a minute, test my pull #434 

Thanks!

**Comment by pvint** [comment]
I went ahead and merged the pull, so it is now in the master branch. If there's any issue let me know!

**Comment by trebmuh** [comment]
@pvint: just to confirm that on a fresh build from git master, ( https://github.com/hydrogen-music/hydrogen/commit/eae444fa49185bcb52a50a5688b67314ccf327b6 ) the issue disappeared. Congrats and thanks Paul!
