### ISSUE TITLE
Save and Restore Input Mode

### ISSUE THREAD

**Issue by 0mk** [hydrogen-music/hydrogen#373]
If I set the input mode to Instrument, there seems to be no way to save and restore this setting for next time. Particularly when using hydrogen under session management (NSM), this is a problem since manual intervention is required, defeating the point of session management.

**Comment by trebmuh** [comment]
Hi @0mk 
please, provide us with an exact step-by-step way of reproducing what you are doing and an explanation of what you are trying to achieve.

**Comment by mauser** [comment]
@trebmuh : The problem is that the state of the "input mode" (drumkit/instrument) is not saved before shutting down hydrogen. When starting hydrogen again, the default value is taken (not the last value which has been set in the last session). 

So at the moment there is no way to make hydrogen always use the "instrument input mode" by default. 

I can see the problem and i'm going to fix it, but i'm not sure if it will be for 0.9.7 or for the next version. I think we should feature-freeze 0.9.7 very soon.

**Comment by trebmuh** [comment]
@mauser: ok, thanks for the hint.

**Comment by 0mk** [comment]
The problem is as Sebastian has described it.  But just to emphasize, it 
is important to save all state (including the state of the input mode) 
when hydrogen is run UNDER NSM (ie as an NSM client). This will 
_potentially_ be in a different code path to saving state when /not/ 
running under NSM. (I haven't checked the source, so Sebastian will know 
if that's true or not).

Cheers,  Martin.

**Comment by mauser** [comment]
Hi,

this issue should be fixed now..

**Comment by 0mk** [comment]
Hi Sebastian.

Thanks for looking into this issue. Sorry for not reporting back earlier.

Unfortunately, the issue is not completely fixed :-(.

When running hydrogen in standalone mode (not under NSM), the fix is 
fine and the input mode is remembered for next time as expected.

When running hydrogen under NSM, the input mode is NOT saved as it 
should be. If the session is closed and then reopened, the input mode is 
set to the input mode that was last set by running hydrogen in 
STANDALONE mode. It should have been set to the input mode that was set 
in the previous NSM session. I hope my explanation is clear. Let me know 
if you need any clarification.

Regards,  Martin

**Comment by 0mk** [comment]
I think the issue can be solved by saving the input mode as part of the 
song data rather than as a global preference. Then the mode can be set 
on a per song basis.

Regards,  Martin.

**Comment by trebmuh** [comment]
_(reopening here since the issue doesn't sound to be 100% covered)_

@0mk : are you able to test if the issue is still present with [1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) ?

**Comment by 0mk** [comment]
Hi Olivier.
I just got your latest comment today as I have been away. I just rebuilt non-session manager and hydrogen 1.0.0-beta1 and then tested this issue. I can confirm, the issue still exists. It might be a good idea to test it yourself so you can see the problem with your own eyes. 

You need to build and install non-session manager  (https://github.com/original-male/non). Then start it. Select 'New' from the menu to create a new session. Call it  'hydrogen test'. Click on 'Add Client to Session' and type in 'hydrogen' into the pop-up box. Click 'OK'. This will start hydrogen.  Then, in hydrogen, select 'Options->InputMode->Instrument'. Now, in NSM, click 'Save'. This will save the session. So next time the session is started, it should start hydrogen with Instrument Mode selected. Next, close the session by clicking on 'Close'. Hydrogen will be shut down. Finally, click on 'hydrogen test' to restart the session. Check the Input Mode. It will be set to 'Drumkit' which is not what we want.

Let me know if your test confirms what I have said.

Regards,  Martin

**Comment by 0mk** [comment]
Hi.
I would just like to ask if anyone is able to take a look at this issue since it is now over year since my last comment. I appreciate that there are a lot of other issues to look at also, so please don' t feel that I am trying to pressure anyone.
Regards,  Martin

**Comment by theGreatWhiteShark** [comment]
Hey Martin,

It's definitely on the TODO list. I'm using NSM too and rewiring stuff after reopening a session is super annoying. 

There is a pull request, which might already cover it (haven't had the time to look into it yet). #675
