### ISSUE TITLE
[FEATURE REQUEST] Export midi files with multiple channels

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#580]
_(from http://hydrogen.popez.org/hcms/node/17532)_

> Is there a way to export a midi file that contains more than 1 channel?  I have combined kits that have drums and accompiniment instruments (bass) to create rhythm tracks to use through my DR-5.  I have placed all of the drums into channel 10 and the bass notes to channel 2 but when exporting a midi file the file only contains the drums.  The bass notes do not show on any midi file editing software I have.  Will this become a supported feature in future releases of Hydrogen?

**Comment by trebmuh** [comment]
a +1 from here http://hydrogen.popez.org/hcms/node/18876

**Comment by trebmuh** [comment]
Done here: #693 . Closing then.

**Comment by gloryofrobots** [comment]
@trebmuh I think this issue is not completely resolved because right now H2 exports all notes into drum channel 10. As I understand this ticket, the issue here is about using bass instrument in a drum patterns and then using exported midi in hardware drum machine. In this case correct channel data for midi tracks is important. I can look into it.

**Comment by trebmuh** [comment]
reopening then

**Comment by gloryofrobots** [comment]
@trebmuh I created #835 to fix this

**Comment by trebmuh** [comment]
Wow, that was fast! Hopefully, it'll make into Master quickly.
Thanks for that.

**Comment by trebmuh** [comment]
:+1:
