### ISSUE TITLE
Can't use custom drumkit

### ISSUE THREAD

**Issue by jnth7n** [hydrogen-music/hydrogen#628]
Hydrogen version *          : 1.0.0 beta
Operating system + version  : Windows 10 Pro 1709 build 16299.492
Audio driver + version      : Realtek High Definition Audio 6.0.1.8467

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

There's a drumkit I use, but whenever I customize it and save it, I can only use it at the current project. After exporting it and loading it in another project, no sound is played from any instrument.

**Comment by mauser** [comment]
Hi! 

Is this only happening with one specific drumkit or with any drumkit? Could you share this drumkit with us?

**Comment by jnth7n** [comment]
Only this one. Yes, I can share it, I uploaded it to Google Drive, the link is this: https://drive.google.com/open?id=18-N6Hhppm_QYkccz0Xx_qwumBZYVhrVH

**Comment by mauser** [comment]
Hi! 

thanks a lot for sharing your drumkit for debugging! I wasn't able to import your drumkit at all in Hydrogen because of an direct crash. I've fixed that now and i'm going to look into the issue further. The crash has happened because there is some unexpected data at the end of your drumkit.xml file, but i'm not sure how it got there :disappointed:

**Comment by jeremyz** [comment]
Hi @jnth7n @mauser  ,

yes there is some junk data at the end of drumkit.xml ?!?!?

but the worst is that the `<instrumentComponent>` xml node has no `<layer>` children.
That node holds the sample filename, min, max, gain and pitch nodes.
Without it, it's impossible to know which sample file to load !!

I've tested exporting && saving && reloading drumkits, it works fine.
looked at the generated drumkit.xml, it's all good.

I don't know how you ended up with a drumkit.xml that has no `<layer>` node   ?
maybe you saved it with a version of hydrogen that had a very buggy drumkit saving code path,
I'm sorry.

**Comment by trebmuh** [comment]
This one is probably fixed by the commit just before this very message. If possible, could you please retest from a fresh build?

**Comment by theGreatWhiteShark** [comment]
Closed due to age. There have been a number of changes to the drumkit export. In case the problem still occurs, please reopen this issue and I'll take care of it
