### ISSUE TITLE
Misleading popup message: "Is not possible to change the pattern size when playing"

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#708]
Hydrogen version *          : git head master https://github.com/hydrogen-music/hydrogen/commit/bbeaed1a5d46414360cbce74e81fbcc0a05e26f6
Operating system + version  : Debian Stretch
Audio driver + version      : whatever

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- create a new song
- create a pattern of size=8 and fill it with things (name the pattern: Blabla)
- create another pattern of size=16 and fill it with things (name tha pattern: Bloblo)
- set Hydrogen control in "pattern" mode and in "loop" mode
- press play

The pattern currently chosen is playing fine.

Now, when clicking on Blabla from Bloblo (or the other way, whatever) to make Hydrogen start to play the other pattern, a "Is not possible to change the pattern size when playing" popup message appeared. This is misleading on 2 points because:

- the user (me) didn't change the pattern size directly
- whatever the popup message is saying, Hydrogen correctly goes from a size=8 pattern to a size=16 pattern

HTH

**Comment by theGreatWhiteShark** [comment]
I also encounter this popup without even starting the playback.
1. create a new song
2. set the size of the current song to e.g. 16
3. create a new song

This is quite awkward. From what I can tell after a quick peek into the source code the GUI creates this popup only if the state of the audio engine is not `STATE_READY` during a change in the pattern size. With the playback stopped it should definitely reside in this state.

**Comment by trebmuh** [comment]
> - create a new song
> - set the size of the current song to e.g. 16
> - create a new song
> 

This is quite strange. Doing that, I don't have any window popping up, and the (second) new song created inherits from the size=16. Not the same for you it seems.

**Comment by mauser** [comment]
Hi,

I also do get those annoying popups frequently. 

From looking at the code, the problems seems to be the poor design of the state management in Hydrogen (state=audio engine transport state). All parts of the GUI are in general not using the state from the audio engine directly, they are updating their view of the current state only if the audio engine has signaled a state change by sending STATE_CHANGE via EventQueue. But sending a STATE_CHANGE event is in no means automatically coupled to a state change in the audio engine. Switching state can be done by modifyng m_audioEngineState directly. So if some code modifies m_audioEngineState without sending a STATE_CHANGE event afterwards, the GUI is out of sync with the current state of the engine. 

The obious solution would be to encapsulate the state change process and tie the change of m_audioEngineState to the update of the event by not allowing to change m_audioEngineState directly. 

I don't know if this is currently the only problem with state mangement or if it is even the cause of this bug, but it is a problem nontheless :)

**Comment by theGreatWhiteShark** [comment]
You are right. Changing the state is something that should be wrapped to keep the GUI synced. But as far as I can see only in `startExportSong()` and `loadDrumkit()` the new state is not pushed to the event queue.

**Comment by thijz** [comment]
i typically see this when a song is playing and i skip to the next/previous song in the playlist (F5/F6) without hitting 'stop' first.  But also this is not 100% reproducible

**Comment by thijz** [comment]
just noticed that i get this when i skip to the next/previous song in my playlist (using F5/F6) and the next song has a different pattern size than the previous one

**Comment by mauser** [comment]
@thijz : I've committed a quick fix for this problem, coud you re-test the issue with the current master branch?

**Comment by thijz** [comment]
Just retested with today's master branch code but unfortunately the problem remains on my setup.
Since my setup is different from what the original poster (@trebmuh ) described i also retested his usecase and also there i still see the popup

**Comment by trebmuh** [comment]
Reproduced the usecase from [my 1st message](https://github.com/hydrogen-music/hydrogen/issues/708#issue-427295305) and the pop up is still here. Using beta2 +

**Comment by mauser** [comment]
Hi! 

Ok, so far so good. I've started with Thijs playlist usecase. I will first improve this fix and then handle the usecase from trebmuh. Thanks for your feedback!

**Comment by mauser** [comment]
@trebmuh: Try the current master branch, hope that your intial problem is now also gone.

**Comment by trebmuh** [comment]
After a build from cfb496c , I can confirm that this bug is resolved now. 
Thanks @mauser !
_closing then_
