### ISSUE TITLE
H2 gets stuck when Delete pattern

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#758]
Hydrogen version *   : v1.0.0 beta Aug 21 2019
Operating system + version  : Ubuntu
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
H2 gets stuck when Deleting a pattern from Pattern list 

Shell message is:
`(E) Hydrogen::sequencer_setNextPattern pos not in patternList range. pos=-1 patternListSize=10`

**Comment by theGreatWhiteShark** [comment]
What? I can confirm the issue and it must be something introduced quite recently.

In addtion the names of new Patterns are not displayed at all.

**Comment by theGreatWhiteShark** [comment]
This bug was introduced during the last commit.

For now could you work/use the second last commit until this issue is fixed?

``` bash
git checkout e13ac780585e173a34c8a6e5accc5d7dd4c52ef3
```

**Comment by oddtime** [comment]
> For now could you work/use the second last commit until this issue is fixed?
> `git checkout e13ac780585e173a34c8a6e5accc5d7dd4c52ef3`

Ok done it.
Should I manually reintroduce the changes I made?

**Comment by theGreatWhiteShark** [comment]
If you are talking about the pull request/feature you are developing, you can harness the power of `git` instead. Using `git rebase -i` you can just drop that specific commit while leaving everything else in place. https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by oddtime** [comment]
Ok

**Comment by mauser** [comment]
Hi! 

Sorry for the trouble.. could you the current master branch? The issue should now be fixed.

**Comment by theGreatWhiteShark** [comment]
Hey mauser, 

Don't worry. Luckily the problem was reported right away.

I still see some irregular behavior. 
When copying an empty pattern the name of the newly generated one is blank. In one instance the size was even increased from 8 to 9 by just copying.

**Comment by mauser** [comment]
Ok, i'll have a look tomorrow.

**Comment by mauser** [comment]
It seems that the copying pattern problem has a different cause, this was already present on the master branch before those changes have been applied. In addition, the bug only appears if the pattern description is empty. I'm going to write a new issue for that problem..

**Comment by mauser** [comment]
@theGreatWhiteShark : The problem with the pattern name should be fixed in the master branch now. But my current fix does not address the issues that you have experienced with the size of patterns. This seems to work for me. Could you check if this is still a problem?

**Comment by mauser** [comment]
@oddtime : Can you confirm that this bug is now fixed?

**Comment by oddtime** [comment]
I confirm it's fixed both delete and copy. I didn't experienced the change of size

**Comment by theGreatWhiteShark** [comment]
Works fine here too. 

Also I was not able to reproduce the change of size. It probably (hopefully) was related to the legacy code.
